# Generated by Django 5.0.6 on 2024-07-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite_info_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AddField(
            model_name='availability',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campsite_info_backend.campsite'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('campsite', 'date')},
        ),
    ]
