# Generated by Django 5.0.7 on 2024-07-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite_info_backend', '0002_availability_campsite_delete_aboutus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='amenities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campsite',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
