# Generated by Django 5.0.7 on 2024-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite_info_backend', '0003_campsite_amenities_campsite_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
